// Code generated by Kitex v0.11.3. DO NOT EDIT.

package imrpc

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	rpc "github.com/lizuowang/gim/service/api/server/kitex_gen/im/rpc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Hello(ctx context.Context, req *rpc.Request, callOptions ...callopt.Option) (r *rpc.Response, err error)
	SendMsgToUser(ctx context.Context, req *rpc.SendMsgReq, callOptions ...callopt.Option) (r *rpc.SendMsgRsp, err error)
	SendMsgToUserByTgid(ctx context.Context, req *rpc.SendMsgByTgidReq, callOptions ...callopt.Option) (r *rpc.SendMsgRsp, err error)
	StopUserClient(ctx context.Context, req *rpc.UserIdReq, callOptions ...callopt.Option) (r *rpc.StopUserClientRsp, err error)
	GetSysInfo(ctx context.Context, callOptions ...callopt.Option) (r *rpc.BytesRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kImRpcClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kImRpcClient struct {
	*kClient
}

func (p *kImRpcClient) Hello(ctx context.Context, req *rpc.Request, callOptions ...callopt.Option) (r *rpc.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Hello(ctx, req)
}

func (p *kImRpcClient) SendMsgToUser(ctx context.Context, req *rpc.SendMsgReq, callOptions ...callopt.Option) (r *rpc.SendMsgRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMsgToUser(ctx, req)
}

func (p *kImRpcClient) SendMsgToUserByTgid(ctx context.Context, req *rpc.SendMsgByTgidReq, callOptions ...callopt.Option) (r *rpc.SendMsgRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMsgToUserByTgid(ctx, req)
}

func (p *kImRpcClient) StopUserClient(ctx context.Context, req *rpc.UserIdReq, callOptions ...callopt.Option) (r *rpc.StopUserClientRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StopUserClient(ctx, req)
}

func (p *kImRpcClient) GetSysInfo(ctx context.Context, callOptions ...callopt.Option) (r *rpc.BytesRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSysInfo(ctx)
}
